// This file was generated by
// $ knex init
// Created ./knexfile.js

// Updated with our config settings.

module.exports = {

  test: {
    client: 'pg',
<<<<<<< HEAD
    connection: 'postgres://localhost/tv_faves_test',
=======
    connection: 'postgres://localhost/tv_faves_test17',
>>>>>>> f617d1d66f5778f98b2686d4787192da376bc658
    migrations: {
      directory: __dirname + '/db/migrations'
    },
    seeds: {
      directory: __dirname + '/db/seeds/test'
    }
  },
  development: {
    client: 'pg',
    debug: true,
<<<<<<< HEAD
    connection: 'postgres://localhost/tv_faves',
=======
    connection: 'postgres://localhost/tv_faves17',
>>>>>>> f617d1d66f5778f98b2686d4787192da376bc658
    migrations: {
      directory: __dirname + '/db/migrations'
    },
    seeds: {
      directory: __dirname + '/db/seeds/development'
    }
  },
  production: {
    client: 'pg',
    connection: process.env.DATABASE_URL,
    migrations: {
      directory: __dirname + '/db/migrations'
    },
    seeds: {
      directory: __dirname + '/db/seeds/production'
    }
  }
<<<<<<< HEAD
}
=======
};
>>>>>>> f617d1d66f5778f98b2686d4787192da376bc658
